name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          # LTS version 1.39 against PHP 7.4, 8.0, 8.1
          - mw: 'REL1_39'
            php: 7.4
          - mw: 'REL1_39'
            php: 8.0
          - mw: 'REL1_39'
            php: 8.1
    runs-on: ubuntu-latest
    steps:
      # check out the repository!
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test extension
        uses: wikiteq/mediawiki-phpunit-action@master
        with:
          type: extension
          php: ${{ matrix.php }}
          mwbranch: ${{ matrix.mw }}
          extension: HoneyPot

